package views;
import Patterns.KullaniciIDGetirme;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import service.Akademisyenİslemleri;
import service.OgrenciIslemleri;

/*

/**
 *
 * @author pc
 */
public class OduncVer extends javax.swing.JFrame {
    DefaultTableModel model;    
    OgrenciIslemleri islemler=new OgrenciIslemleri();
    Akademisyenİslemleri akademisyenİslemleri=new Akademisyenİslemleri();
    
    KitaplariListele listele=new KitaplariListele();
    KullaniciIDGetirme id = KullaniciIDGetirme.getKullanici();
    KullaniciIDGetirme kullanici = KullaniciIDGetirme.getKullanici();
    
public OduncVer() {
        initComponents();
        listele.model=(DefaultTableModel)kitapTablosu.getModel();
        listele.kitaplariGoruntule();
        txUyeId.setText(String.valueOf(id.getId()));
       
        String unvan = kullanici.getUnvan();
        
        if(unvan.equals("Akademisyen")){
            buttonSatinAl.setVisible(true);
        }else{
            buttonSatinAl.setVisible(false);
            buttonSatinAl.setEnabled(false);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        kitapTablosu.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
     

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txKitapAdiAra = new javax.swing.JTextField();
        buttonAra = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txUyeId = new javax.swing.JTextField();
        txKitapId = new javax.swing.JTextField();
        buttonOduncAl = new javax.swing.JButton();
        buttonSatinAl = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kitapTablosu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kitap Adi:");

        txKitapAdiAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txKitapAdiAraActionPerformed(evt);
            }
        });

        buttonAra.setText("ARA");
        buttonAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAraActionPerformed(evt);
            }
        });

        jLabel3.setText("Üye ID:");

        jLabel4.setText("Kitap ID:");

        buttonOduncAl.setText("Ödünç Al");
        buttonOduncAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOduncAlActionPerformed(evt);
            }
        });

        buttonSatinAl.setText("Satın Al");
        buttonSatinAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSatinAlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonOduncAl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txKitapId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txUyeId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73)
                .addComponent(buttonSatinAl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 132, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txUyeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txKitapId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSatinAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOduncAl, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        kitapTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kitap İd", "Kitap adı", "Yazar", "Sayfa Sayısı", "Yayın Evi", "Kitap Türü", "Kategori", "Basın Yılı", "Kitaplık Adı", "Raf Adı", "Barkod Sayısı", "Ekleyen İd", "Eklenme Tarihi", "Durum"
            }
        ));
        kitapTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitapTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kitapTablosu);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-2-icon.png"))); // NOI18N
        jLabel2.setText("GERİ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(114, 114, 114)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txKitapAdiAra, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(buttonAra, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAra, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txKitapAdiAra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAraActionPerformed
     
       
        listele.kitaplariGoruntule();
        
        
        
    }//GEN-LAST:event_buttonAraActionPerformed

    private void kitapTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitapTablosuMouseClicked
        int secilen_satir=kitapTablosu.getSelectedRow();
        txKitapId.setText(listele.model.getValueAt(secilen_satir, 0).toString());
        txKitapAdiAra.setText(listele.model.getValueAt(secilen_satir, 1).toString());
       
        
    }//GEN-LAST:event_kitapTablosuMouseClicked

    private void txKitapAdiAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txKitapAdiAraActionPerformed
       
    }//GEN-LAST:event_txKitapAdiAraActionPerformed

    private void buttonOduncAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOduncAlActionPerformed
        int uye_id = Integer.parseInt(txUyeId.getText());
        int kitap_id = Integer.parseInt(txKitapId.getText());
        String kullaniciUnvan = kullanici.getUnvan();
        
        int gonderilenOgrenciId = 0;
        int gonderilenAkademisyenId = 0;
        if(kullaniciUnvan.equals("Öğrenci")){
            gonderilenOgrenciId = uye_id;
        }else if(kullaniciUnvan.equals("Akademisyen")){
            gonderilenAkademisyenId = uye_id;
        }
        try {
        // Daha önce kitap almış mı kontrolü
        
        // Satırın durumunu kontrol et (örneğin, 14. kol durumu)
        String kitapDurumu = (String) kitapTablosu.getValueAt(kitapTablosu.getSelectedRow(), 13);
           
        
        if (!kitapDurumu.equals("Kitap Bulunuyor")) {
            JOptionPane.showMessageDialog(null, "Bu Kitap Şuan Mevcut Değil.");
        } 
        else {
            // Şuanki tarihi almak için Calendar sınıfını kullanalım
            Calendar cal = Calendar.getInstance();
            java.util.Date today = cal.getTime();
            java.sql.Date verilis_tarihi = new java.sql.Date(today.getTime());

            // İade tarihini 2 hafta sonrasına ayarla (sadece gün bazında işlem)
            cal.add(Calendar.DAY_OF_YEAR, 14); // 14 gün (2 hafta) ekliyoruz
            java.sql.Date iade_tarihi = new java.sql.Date(cal.getTimeInMillis());

            // İade tarihi geçmiş mi kontrolü
            if (islemler.iadeTarihiGecmisMi(uye_id, iade_tarihi)) {
                JOptionPane.showMessageDialog(null, "İade tarihiniz geçmiştir");
            } else {
                // Ödünç verme işlemi
                islemler.OduncVer(kitap_id, gonderilenOgrenciId, gonderilenAkademisyenId, verilis_tarihi);
                JOptionPane.showMessageDialog(null, "Kitap başarıyla ödünç alındı");
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(OduncVer.class.getName()).log(Level.SEVERE, null, ex);
    }

                                              

    }//GEN-LAST:event_buttonOduncAlActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        ÖğrenciEkrani ogreEkrani=new ÖğrenciEkrani();
        ogreEkrani.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void buttonSatinAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSatinAlActionPerformed
        
        int akademisyen_id = Integer.parseInt(txUyeId.getText());
        int kitap_id = Integer.parseInt(txKitapId.getText());
        String kitapDurumu = (String) kitapTablosu.getValueAt(kitapTablosu.getSelectedRow(), 13);

        
        // Satırın durumunu kontrol et (örneğin, 14. kol durumu)
        if (!kitapDurumu.equals("Kitap Bulunuyor")) {
            JOptionPane.showMessageDialog(null, "Bu Kitap Şuan Mevcut Değil.");
        } else {
            // Şuanki tarihi almak için Calendar sınıfını kullanalım
            Calendar cal = Calendar.getInstance();
            java.util.Date today = cal.getTime();
            
            akademisyenİslemleri.satinAl(akademisyen_id, kitap_id, today);
            JOptionPane.showMessageDialog(null, "Kitap başarıyla satın alındı");
            
        }

    }//GEN-LAST:event_buttonSatinAlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OduncVer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAra;
    private javax.swing.JButton buttonOduncAl;
    private javax.swing.JButton buttonSatinAl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kitapTablosu;
    private javax.swing.JTextField txKitapAdiAra;
    private javax.swing.JTextField txKitapId;
    private javax.swing.JTextField txUyeId;
    // End of variables declaration//GEN-END:variables
}
